---
- name: microk8s | create browsertrix repo
  ansible.builtin.git:
    repo: "https://github.com/webrecorder/browsertrix-cloud"
    dest: "{{ browsertrix_cloud_home }}"
    clone: true
    update: true
    force: true
    version: main
  tags:
    - helm_upgrade

- name: microk8s | Make repos git safe
  ansible.builtin.command: git config --global --add safe.directory "{{ browsertrix_cloud_home }}"
  become: true
  changed_when: false
  tags:
    - helm_upgrade

- name: microk8s | grant permissions on deploy user
  ansible.builtin.file:
    path: "{{ browsertrix_cloud_home }}"
    state: directory
    owner: '{{ microk8s_user }}'
    group: '{{ microk8s_user }}'
    follow: false
    recurse: true
    mode: 0775
  tags:
    - helm_upgrade

- name: d_ocean | helm | output values yaml
  ansible.builtin.template:
    src: btrix_values.j2
    dest: "{{ microk8s_user_home }}/values.yaml"
    mode: u+rw
  tags:
    - helm_upgrade

- name: microk8s | helm | deploy btrix
  ansible.builtin.command: helm upgrade --install -f ./chart/values.yaml -f {{ microk8s_user_home }}/values.yaml btrix ./chart/
  args:
    chdir: "{{ browsertrix_cloud_home }}"
  register: helm_result
  become: true
  become_user: "{{ microk8s_user }}"
  changed_when: helm_result.rc == 0
  tags:
    - helm_upgrade
