---
# configure_plugins file for microk8s
- name: microk8s | enable plugins
  ansible.builtin.command:
    cmd: "microk8s.enable {{ microk8s_plugin.key }}"
  with_dict: "{{ microk8s_plugins }}"
  loop_control:
    loop_var: microk8s_plugin
    label: "{{ microk8s_plugin.key }}"
  when:
    - microk8s_plugins is defined
    - microk8s_plugin.value
    - microk8s_plugin.key != "registry"
    - microk8s_plugin.key != "dns"
  register: microk8s_cmd_result
  changed_when:
    - "'Addon {{ microk8s_plugin.key }} is already enabled'
      not in microk8s_cmd_result.stdout"

- name: microk8s | disable plugins
  ansible.builtin.command:
    cmd: "microk8s.disable {{ microk8s_plugin.key }}"
  with_dict: "{{ microk8s_plugins | default({}) }}"
  loop_control:
    loop_var: microk8s_plugin
    label: "{{ microk8s_plugin.key }}"
  register: microk8s_cmd_result
  changed_when:
    - "'Addon {{ microk8s_plugin.key }} is already disabled'
      not in microk8s_cmd_result.stdout"
  when:
    - microk8s_plugins is defined
    - not (microk8s_plugin.value | bool)
    - microk8s_plugin.key != "registry"

- name: microk8s | Enable registry
  ansible.builtin.command:
    cmd: "microk8s.enable registry:size={{ microk8s_registry_size }}"
  register: microk8s_cmd_result
  changed_when:
    - "'Addon registry is already enabled' not in microk8s_cmd_result.stdout"
  when:
    - microk8s_plugins is defined
    - microk8s_plugins.registry is defined
    - (microk8s_plugins.registry | bool)

- name: microk8s | Disable registry
  ansible.builtin.command:
    cmd: "microk8s.disable registry:size={{ microk8s_registry_size }}"
  register: microk8s_cmd_result
  changed_when:
    - "'Addon registry is already disabled' not in microk8s_cmd_result.stdout"
  when:
    - microk8s_plugins is defined
    - microk8s_plugins.registry is defined
    - not (microk8s_plugins.registry | bool)

- name: microk8s | Enable DNS
  ansible.builtin.command:
    cmd: 'microk8s.enable dns:{{ microk8s_dns_servers | join(",") }}'
  register: microk8s_cmd_result
  changed_when:
    - "'Addon dns is already enabled' not in microk8s_cmd_result.stdout"
  when:
    - microk8s_plugins is defined
    - microk8s_plugins.dns is defined
    - (microk8s_plugins.dns | bool)
