---
# tasks file for microk8s

- name: microk8s | install microk8s
  ansible.builtin.import_tasks:
    file: install.yml
  tags:
    - always
    - microk8s

- name: microk8s | configure users
  ansible.builtin.include_tasks:
    file: configure_groups.yml
  when:
    - microk8s_users is defined
    - microk8s_users not in ([], None, '', omit)
  tags:
    - microk8s
    - microk8s.users
    - notest

- name: microk8s | configure plugins
  ansible.builtin.include_tasks:
    file: configure_plugins.yml
  run_once: true
  when:
    - microk8s_plugins is defined
  tags:
    - microk8s
    - microk8s.plugins
