---
# tasks file for microk8s
- name: microk8s | install microk8s
  ansible.builtin.import_tasks:
    file: install.yml

- name: microk8s | configure users
  ansible.builtin.include_tasks:
    file: configure_groups.yml
  when:
    - microk8s_users is defined
    - microk8s_users not in ([], None, '', omit)

- name: microk8s | configure plugins
  ansible.builtin.include_tasks:
    file: configure_plugins.yml
  run_once: true
  when:
    - microk8s_plugins is defined

- name: microk8s | install browsertrix
  ansible.builtin.include_tasks:
    file: configure_helm.yml
  run_once: true
  when:
    - microk8s_plugins is defined
