---
# defaults file for microk8s
#
# version management
microk8s_version: "2.20/stable"
microk8s_disable_snap_autoupdate: false

# plugin configuration
microk8s_dns_resolvers: 149.112.112.112,9.9.9.9
registry_size: 20Gi
microk8s_plugins:
  dns: "{{ microk8s_dns_resolvers }}"     # CoreDNS
  host-access: true                       # Allow Pods connecting to Host services smoothly
  ingress: true                           # Ingress controller for external access
  metrics-server: true                    # K8s Metrics Server for API access to service metrics
  rbac: true                              # Role-Based Access Control for authorisation
  storage: true                           # Storage class; allocates storage from host directory
  registry: "size={{ registry_size }}"    # Private image registry exposed on localhost:32000
  dashboard: true                         # The Kubernetes dashboard
  gpu: false                              # Automatic enablement of Nvidia CUDA
  helm3: true                             # Helm 3 - Kubernetes package manager

helm3_repositories:
  - name: stable
    url: https://charts.helm.sh/stable

# users to make members of microk8s group
users: []

# enable high-availability?
microk8s_enable_ha: false

# hostgroup whose members will form high-availability cluster
microk8s_group_ha: "microk8s_ha"

# regex to select IP address for joining nodes in HA setup
microk8s_ip_regex_ha: "([0-9]{1,3}[\\.]){3}[0-9]{1,3}"
