---
- name: setup digital ocrean
  hosts: localhost
  connection: local
  remote_user: "root"
  become: true
  gather_facts: false
    #  vars_files:
    # - "../group_vars/do/vault.yml"
  vars:
    #    ansible_python_interpreter: /usr/bin/python
    droplet_image: "ubuntu-20-04-x64"
    droplet_size: "s-1vcpu-1gb"
    droplet_region: "sfo3"
    
  tasks:
    - name: d_ocean | Create a new DigitalOcean Kubernetes cluster in New York 1
      community.digitalocean.digital_ocean_kubernetes:
        state: present
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        name: webrecorder
        region: nyc1
        node_pools:
          - name: webrecorder-workers
            size: s-1vcpu-2gb
            count: 3
        return_kubeconfig: true
        wait_timeout: 600
        tags: webrecorder
      register: webrecorder_cluster
      ignore_errors: true

    - name: d_ocean | Show the kubeconfig for the cluster we just created
      debug:
        msg: "{{ webrecorder_cluster.data.kubeconfig }}"
      ignore_errors: true

    - name: d_ocean | add public ssh key to digitalocean account
      community.digitalocean.digital_ocean_sshkey:
        name: "my_laptop"
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        ssh_pub_key: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"
        state: present
      register: sshkey_result
      ignore_errors: true

    - name: Get information about an existing DigitalOcean Kubernetes cluster
      community.digitalocean.digital_ocean_kubernetes_info:
        oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
        name: webrecorder
        return_kubeconfig: true
      register: my_cluster
      ignore_errors: true

    - ansible.builtin.debug:
        msg: "Cluster name is {{ my_cluster.data.name }}, ID is {{ my_cluster.data.id }}"
      ignore_errors: true

    - ansible.builtin.debug:
        msg: "Cluster kubeconfig is {{ my_cluster.data.kubeconfig }}"
      ignore_errors: true

    - name: Create a Load Balancer and associate it with a tag
      community.digitalocean.digital_ocean_load_balancer:
        oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
        state: present
        name: webrecorder
        tag: k8s
        region: nyc1
      ignore_errors: true

    - name: Get name from load balancer id
      community.digitalocean.digital_ocean_load_balancer_info:
        oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
      register: resp_out
    - debug:
        var: resp_out.stdout

