---
- name: deploy browsertrix on digital ocrean
  hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
   - "../group_vars/do/main.yml"
   - "../group_vars/do/private.yml"
  tasks:

    - name: d_ocean | install doctl and helm
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - helm
        - doctl

    - name: d_ocean | test for existing mongodb
      ansible.builtin.command: doctl db list
      changed_when: false
      failed_when: false
      tags: helm_upgrade
      register: db_check

    - name: d_ocean | create mongodb database
      ansible.builtin.command: doctl databases create {{ btrix_db }} --region {{ droplet_region }} --engine mongodb --version 5 --output json
      async: 1800
      poll: 60
      register: webrecorder_database
      tags: helm_upgrade
      when: db_check.stdout.find('{{ btrix_db }}') == -1

    - name: d_ocean | drop mongodb database
      community.digitalocean.digital_ocean_database:
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        state: absent
        region: "{{ droplet_region }}"
      tags: never

    - name: d_ocean | copy the mongodb info doctl created to tmp directory
      ansible.builtin.copy:
        content: "{{ webrecorder_database.stdout }}"
        dest: "/tmp/{{ lookup('pipe', 'date +%Y-%m-%d@$H:%M:%S') }}d_ocean_btrix_db_url.txt"
      delegate_to: localhost
      ignore_errors: true

    - name: d_ocean | Create new Space
      community.digitalocean.digital_ocean_spaces:
        name: "{{ space_name }}"
        state: present
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        aws_access_key_id: "{{ lookup('env', 'DO_AWS_ACCESS_KEY')}}"
        aws_secret_access_key: "{{ lookup('env', 'DO_AWS_SECRET_KEY')}}"
        region: "{{ droplet_region }}"
      register: webrecorder_space
      tags: helm_upgrade
      ignore_errors: true

    - name: d_ocean | drop a Space
      community.digitalocean.digital_ocean_spaces:
        name: "{{ space_name }}"
        oauth_token: "{{ lookup('env', 'DO_API_TOKEN') }}"
        state: absent
      tags: never

    - name: d_ocean | test for existing k8s cluster
      command: doctl k8s cluster list
      changed_when: false
      failed_when: false
      register: cluster_check

    - name: d_ocean | create a kubernetes cluster in {{ droplet_region }}
      command: doctl kubernetes cluster create {{ k8s_cluster }} --1-clicks ingress-nginx,cert-manager --node-pool "name=main-app;size={{ droplet_size }};label=nodeType=main;count=2,name=crawling;size=c-4;label=nodeType=crawling;taint=nodeType=crawling:NoSchedule;auto-scale=true;min-nodes=1;max-nodes=3;count=1" --region={{ droplet_region }}
      async: 1800
      poll: 60
      changed_when: false
      when: cluster_check.stdout.find('{{ k8s_cluster }}') == -1

    - name: d_ocean | Get information about our cluster
      community.digitalocean.digital_ocean_kubernetes_info:
        oauth_token: "{{ lookup('ansible.builtin.env', 'DO_API_TOKEN') }}"
        name: "{{ k8s_cluster }}"
        return_kubeconfig: true
      register: my_cluster
      tags: helm_upgrade

    - name: d_ocean | print information about an existing DigitalOcean Kubernetes cluster
      ansible.builtin.debug:
        msg: "Cluster name is {{ my_cluster.data.name }}, ID is {{ my_cluster.data.id }}"
      ignore_errors: true

    - name: d_ocean | save kubectl config to kube_dir
      command: doctl kubernetes cluster kubeconfig save {{ my_cluster.data.id }}
      changed_when: false
      tags: helm_upgrade

    - name: d_ocean | deploy btrix
      kubernetes.core.helm:
        release_name: btrix
        release_namespace: default
        kubeconfig: ~/.kube/config
        chart_ref: ../../chart/
        values:
          mongo_local: false
          mongo_auth:
            db_url: "{{ btrix_db_url }}"
            # determine why variable below does not "stick"
            # db_url: "{{ webrecorder_database.stdout | from_json | json_query('[0].private_connection.uri') }}"
            username: root
            password: example
          minio_local: false

          storages:
          - name: "default"
            access_key: "{{ lookup('env', 'DO_AWS_ACCESS_KEY')}}"
            secret_key: "{{ lookup('env', 'DO_AWS_SECRET_KEY')}}"

            endpoint_url: "{{ webrecorder_space.data.space.space_url }}"

          rwp_base_url: "{{ domain_name }}"
          superuser:
            email: "{{ email_address }}"
        values_files:
          - ../../chart/values.yaml
      tags: helm_upgrade
      ignore_errors: true

    - name: d_ocean | get loadbalancer info from doctl
      ansible.builtin.command: doctl k8s cluster list-associated-resources {{ my_cluster.data.id }} --format LoadBalancers --output json
      register: my_lb

    - name: d_ocean | copy the loadbalancer uuid info from doctl
      ansible.builtin.copy:
        content: "{{ my_lb.stdout }}"
        dest: "/tmp/{{ lookup('pipe', 'date +%Y-%m-%d@$H:%M:%S') }}d_ocean_lb_uuid.txt"
      delegate_to: localhost
      ignore_errors: true

    - name: d_ocean | Print return information for loadbalancer
      ansible.builtin.set_fact:
        lb_info: "{{ my_lb.stdout | from_json }}"

    - name: d_ocean | grab loadbalancer ip using doctl
      ansible.builtin.command: doctl compute load-balancer get --format IP "{{ lb_uuid }}"
      register: loadbalancer_ip
      ignore_errors: true

    - name: d_ocean | copy the loadbalancer info doctl created
      ansible.builtin.copy:
        content: "{{ loadbalancer_ip.stdout }}"
        dest: "/tmp/{{ lookup('pipe', 'date +%Y-%m-%d@$H:%M:%S') }}d_ocean_loadbalancer_ip.txt"
      delegate_to: localhost
      ignore_errors: true

    - name: d_ocean | register the dns of your webrecorder
      command: doctl compute domain records create --record-type A --record-name "btrixcloud-{{ ip_name | default('test1') }}" --record-data "{{ loadbalancer_ip }}" "{{ domain_name }}"
      changed_when: false
      failed_when: false
      register: cluster_check
